apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: node1-gitops
  description: This is GitOps manifest for node1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: node1
    backstage.io/kubernetes-id: node1 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: node1   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:node1
