apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node1
  janus-idp.io/tekton: node1
  backstage.io/kubernetes-id: node1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node1
resources:
- deployment.yaml
- route.yaml
- service.yaml
