apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: node1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node1 
  name: node1
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: node1
    weight: 100 
