apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node1 
  name: node1
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node1 
